name: Hello World Workflow

on: 
  workflow_dispatch:  # Allows manual execution

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello world!"
